### ISSUE TITLE
Broken Hyperlinks

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-gov#107]
@cbukovac @katielotterman 
There are two broken links here:
https://www.fedramp.gov/fedramp-connect-were-now-accepting-business-cases-for-the-second-round-of-jab-prioritization/

The broken links are "Business Case submissions" and "FedRAMP Business Case:"  Either remove the hyperlinks or link to sample business case.

**Comment by cbukovac** [comment]
@rhoesing we're current working through all of the old blogs and fixing all the links, this one will be updated today. Let me know if you'd like to see our analysis of what needs to be fixed/how we're tracking our progress.
