### ISSUE TITLE
[Violation] Avoid using document.write().

### ISSUE THREAD

**Issue by thecapacity** [GSA/fedramp-gov#110]
I get an error in my javascript console for `[Violation] Avoid using document.write().`

It looks like it's from this line in the footer;
    `document.write(new Date().getFullYear());`

It looks like (from a number of web hits including this one); https://developers.google.com/web/updates/2016/08/removing-document-write
   - that this mode of updating is deprecated

Possible solution, tag the footer with an `#year` ID and then use something like this in the jQuery page load sectin; `$("#year").val(months[new Date().getFullYear()])`

**Comment by cbukovac** [comment]
@thecapacity Hi Jay, is this an urgent issue/fix? I'm not tracking it, but I'm looping in @margo29 to see if she sees this and can help.

**Comment by margo29** [comment]
@thecapacity - Will certainly look into this and update accordingly!

**Comment by thecapacity** [comment]
@cbukovac definitely not urgent!

**Comment by margo29** [comment]
@thecapacity - Jay, I tried that other version but it wasn't working either. So currently I have placed in the year until I can find a better solution.
