### ISSUE TITLE
Broken links to 18F open source policy and team practices in README

### ISSUE THREAD

**Issue by Harmon758** [GSA/fedramp-gov#194]
> ## 18F Open Source Policy
> 
> This repository contains the official [Open Source Policy](policy.md) of [18F](https://18f.gsa.gov/) (a digital delivery team within the [General Services Administration](http://gsa.gov)).
> 
> **[Read 18F's Open Source Policy.](policy.md)**
> 
> ### 18F Team Guidance
> 
> For 18F team members, we have guidance on how 18F puts this policy into practice, and how we handle the narrow situations where we may delay or withhold the release of source code.
> 
> **[18F's open source team practices.](practice.md)**

This seems to be copied from https://github.com/18F/open-source-policy/blob/master/README.md, but this repository does not have the corresponding policy.md and practice.md.

**Comment by shivaalipour** [comment]
@rhoesing updated link 4/9/24

**Comment by shivaalipour** [comment]
links update and appropriate files create
