### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by wslack** [GSA/fedramp-gov#47]
@line47 is working on a branch to add search support

Preview https://federalist-proxy.app.cloud.gov/preview/gsa/fedramp-gov/searchgov-api/search-results/?search=ato

**Comment by line47** [comment]
I'm thinking it would be a good idea to add https://github.com/jekyll/jekyll-sitemap to the Fedramp site to generate an XML sitemap for search.gov to use

**Comment by wslack** [comment]
@line47 That's a good question for @cbukovac - it looks like search was on their long-term roadmap and I'm not sure how much priority they have for it.

**Comment by cbukovac** [comment]
@wslack search is definitely a priority, it just wasn't part of on V1 site/launch plan. If you and @line47 think this is the best way to add a search function to the website, I'm fine with it. I don't know what the other options are, so I don't have an opinion.

**Comment by line47** [comment]
Search is working fairly well now 👍  I think we still need to get a sitemap added to the site. I can open a separate issue for that work or lump it in with the search results as they are definitely closely related.

**Comment by line47** [comment]
I'm unsure where you'd like search to fit into the design. I've included a screenshot of how it is at the moment. @cbukovac Let me know if you'd like help with figuring out your top header. 

![screen shot 2018-02-08 at 10 44 11 am](https://user-images.githubusercontent.com/1449852/35981887-692116c0-0cbc-11e8-85e7-f80a2e0c62b4.png)

**Comment by cbukovac** [comment]
@line47 I think that looks fine for now and if we want to move/adjust it later on I can work with my team to do that. Thanks for your help with this, I'm going to merge your pull request now.
