### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by wslack** [GSA/fedramp-gov#49]
We should consider protecting the master branch and requiring changes to come in via pull requests to avoid surprise issues during the site launch process.

**Comment by cbukovac** [comment]
I think the reality of the fedramp.gov site is that in a month, or probably less, it will go back to business as usually with only myself and Katie Lotterman ever touching the site. We can temporarily add this protection, but assuming they're aren't objections by Matt/Jay, if I just have to fix a comma or a typo in a blog, I'm going to do it in master. The original post and other bigger updated will clearly always be done in demo.

**Comment by wslack** [comment]
🤷‍♂️ if not concerned about it, happy not to put it in! will close for now
