### ISSUE TITLE
Urgent: Build problem with demo 

### ISSUE THREAD

**Issue by cbukovac** [GSA/fedramp-gov#53]
The latest build of the demo branch didn't work and all I added was a blog post. Here is what @wslack identified as the problem 

source 'https://rubygems.org'

gem 'jekyll-menus'
gem "github-pages", group: :jekyll_plugins
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'

**Comment by wslack** [comment]
We found discussion of the issue here: https://github.com/github/pages-gem/issues/399

**Comment by wslack** [comment]
Jonathan (Federalist Dev) is setting the site up locally to see if he can reproduce and fully diagnose

**Comment by wslack** [comment]
This happens, we think, when:

 - a custom domain is set
 - a specific jekyll plugin is used (that has a bug)
 - Jekyll env is set to production.

**Comment by wslack** [comment]
James is working to remove the `jekyll env` setting

**Comment by wslack** [comment]
Update: James's fix resolved this. @jmhooper is still working to understand the bug in the plugin that fires this.

**Comment by cbukovac** [comment]
@wslack looks like this is all taken care of? I'm going to close this issue if you agree. Thanks!

**Comment by wslack** [comment]
@cbukovac I can't figure out when the fix was merged from `demo` to `master` but as long as that happened you can close this!

**Comment by wslack** [comment]
Found it: https://github.com/GSA/fedramp-gov/pull/68

**Comment by wslack** [comment]
Ok, @jseppi is will now redploy the code that originally triggered the bug.

**Comment by cbukovac** [comment]
Ok, I assume I should do a build after he's deployed it to make sure nothing happens?

**Comment by wslack** [comment]
yes!

**Comment by wslack** [comment]
@jseppi will let you know when he's done that

**Comment by cbukovac** [comment]
@wslack @jseppi great, thank you!!

**Comment by jseppi** [comment]
The build container has been deployed. Please try a build, @cbukovac, and let me know if anything goes awry.

**Comment by cbukovac** [comment]
@wslack @jseppi site broke again. Please let me know if there is anything I can do to help resolve this.

**Comment by wslack** [comment]
this is now fixed

**Comment by wslack** [comment]
The site is back up and the code change to remove the offending gem is coming into demo.

**Comment by wslack** [comment]
we are testing the change in demo

**Comment by wslack** [comment]
@cbukovac and @rhoesing https://demo.fedramp.gov/ is working which means Adam's fix worked. I'd like to merge that to `master` now.

**Comment by cbukovac** [comment]
@wslack fine by me!

**Comment by cbukovac** [comment]
Just seeing the PR failed, I'll wait to see what you all decide there.

**Comment by wslack** [comment]
@cbukovac that was my bad, but `master` is now FIXED. I don't expect this bug to reoccur.

**Comment by wslack** [comment]
I can remove the protections on master now if you want; it depends on if you want to make every edit go through `demo` or not

**Comment by cbukovac** [comment]
Let's keep the protection for now/while we solve search and then we can remove it later on.

**Comment by cbukovac** [comment]
@wslack ok with me closing this issue? Seems like we've gotten this figured out/resolved?

**Comment by wslack** [comment]
yes!
