### ISSUE TITLE
Document Removal - Designations for Cloud Service Providers

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-gov#537]
@shivaalipour As part of updating the [Marketplace](https://marketplace.fedramp.gov/products) we created the [About Marketplace Page](https://www.fedramp.gov/about-marketplace/) which supersedes {Designations for Cloud Service Providers](https://www.fedramp.gov/assets/resources/documents/FedRAMP_Marketplace_Designations_for_Cloud_Service_Providers.pdf).  Can you please remove  the document in our assets and update the URL in other posts on the website that reference the previous document?  I did a quick search and found 6 references.

**Comment by shivaalipour** [comment]
- Best practice for blogs and broken links
- how often to archive 

Update 2022 blog

**Comment by shivaalipour** [comment]
all links updated

**Comment by shivaalipour** [comment]
@david-waltermire adding broken link scan
