### ISSUE TITLE
Marketplace Numbers not aligned

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-gov#539]
The screen shot below from fedramp.gov does not match the numbers on current FedRAMP Marketplace.

<img width="1512" alt="Screenshot 2023-08-16 at 2 04 40 PM" src="https://github.com/GSA/fedramp-gov/assets/14299630/65525eeb-2e96-420c-adde-794ac04710ce">

**Comment by echovanderhyden** [comment]
i pushed this to the demo branch.  please review.
