### ISSUE TITLE
Image that appears with links

### ISSUE THREAD

**Issue by cbukovac** [GSA/fedramp-gov#61]
@margo29 when someone posts a link from the website into slack or an imessage the image of the mountains still comes up (see image below). Can we change this? Thanks! 

![screen shot 2018-02-08 at 9 58 09 am](https://user-images.githubusercontent.com/25774107/35979732-159a5da4-0cb7-11e8-9f44-e748b269f6c3.png)

**Comment by cbukovac** [comment]
@margo29 can this be a different image for each page or will it always be the same image? If it's always one image can we actually just make it the FedRAMP logo?

**Comment by margo29** [comment]
@cbukovac - suggest we keep as universal?

**Comment by cbukovac** [comment]
@margo29 For now let's just have a universal image as the quick fix and we can talk about other options later.
