### ISSUE TITLE
Search Functionality 

### ISSUE THREAD

**Issue by JohnWHamilton** [GSA/fedramp-gov#71]
fedramp.gov currently doesn't support the capability to search all contents hosted on the site that includes information within the marketplace

**Comment by cbukovac** [comment]
@JohnWHamilton the Marketplace is a different site and won't be searchable from the fedramp.gov. I've talked with Mike about improving the functionality of search on the Marketplace before, but he hasn't been able to get support from Federalist to improve it's capabilities.
