### ISSUE TITLE
iPhone CSS issue

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-gov#72]
Using my iPhone 7 - iOS 11.2.2 I get the image below.  This was under "Partners We Serve" in nav and then subheading "Cloud Service Providers"
![screen shot 2018-02-08 at 12 35 49 pm](https://user-images.githubusercontent.com/14299630/35988559-caf4ceb8-0ccc-11e8-949a-3485ea9a9213.png)

**Comment by rhoesing** [comment]
Using Google Chrome^^

**Comment by cbukovac** [comment]
@margo29 can you look into this when you are checking into the navigation bar issue as well?

**Comment by margo29** [comment]
@cbukovac - not a problem, I will be sure to add that to my task list!

**Comment by margo29** [comment]
@cbukovac  & @rhoesing -

I have corrected this issue along with others. Please test again and let me know if you see any further problems.
