### ISSUE TITLE
Search Brings up 404 Pages

### ISSUE THREAD

**Issue by cbukovac** [GSA/fedramp-gov#73]
@line47 @wslack the search function is bringing up a bunch of pages that result in 404 errors - it's searching pages that don't exist anymore. Can we take this off our site while we get it fixed?

**Comment by cbukovac** [comment]
I've reverted that commit in master and removed the search function. 

@wslack has recommended "either merge it to `demo` to test out or open a new PR to `master` and ask for fixes there." 

I'm confused why the search function we added would suddenly work in demo if we haven't changed anything about it?

**Comment by line47** [comment]
That sounds good, I think the indexing needs to catch up to the site moving (the sitemap.xml should help with that) You could merge to demo and wait to add search until the indexing is updated. That might be the best route to go.

**Comment by wslack** [comment]
@cbukovac its more that I thought we could troubleshoot it in `demo` or in a preview branch to ensure its good before merging to master.

**Comment by cbukovac** [comment]
@line47 @wslack - @margo29 has resolved the conflicts and deployed the search function on demo, however it isn't working and any search just comes up with a 404 page. Could you help us with this? Or do you have any suggestions?

**Comment by wslack** [comment]
Checking if Scott has capacity (he's not staffed on federalist anymore)

**Comment by margo29** [comment]
@wslack - any luck with Scott?

**Comment by dawnpm** [comment]
Hi folks, we have the site, along with the set of pdfs, indexed into our new index and ready to review. Who's the right person to work with on getting approval to switch the live search from Bing to our index? thanks.

**Comment by thecapacity** [comment]
Thanks @dawnpm - I wonder if maybe some of the links are coming from the PDFs?

@cbukovac 's the right person to coordinate with, along with @wslack 

FWIW I think this is the branch where @line47 worked out the initial search feature; https://github.com/GSA/fedramp-gov/tree/searchgov-api

**Comment by cbukovac** [comment]
Hi @dawnpm! We're working with @wslack right now to get the search function working on our demo site so we can test it before pushing it to the live website. @thecapacity is right, myself and @margo29 are the people to work with, but we haven't done this before so I'll schedule a quick meeting for us to chat about this after we've gotten the search working in demo if that's ok with you!

**Comment by dawnpm** [comment]
Sounds good. I can take a look at what you've got in the demo site, and see if it's a code issue or a configuration issue.

**Comment by margo29** [comment]
@cbukovac - of course!

@dawnpm - from my findings I found the following code at  assets/js/index.js,  and the html pages: _layouts/search-results.html,  _includes/header.html . Those may be good starting points to help you figure out what the issue is. I believe it might be just an API? But happy to help out any further if I can!

**Comment by dawnpm** [comment]
Thanks @margo29 - the search isn't using our service: https://github.com/GSA/fedramp-gov/blob/1bb2321dc33b9396edf16d3ac68293073707a055/_includes/header.html#L45

In order to use our service, the form action needs to be pointing at "https://search.usa.gov/search", and the form code needs to include a few other required parameters. There's example code in our admin center, but it looks like Scott is the only one with access currently. Who should be able to access the search admin center? Thanks.

**Comment by line47** [comment]
Hey folks, I can take a look at this today. 👍

**Comment by line47** [comment]
See PR https://github.com/GSA/fedramp-gov/pull/109/

**Comment by cbukovac** [comment]
@line47 Thanks so much for your help!

**Comment by cbukovac** [comment]
@margo29 could we increase the size of the search box so that longer phrases would be seen completely? Also, is there a way to change the boxes that appear around the search term to be highlighting or quotes instead?

**Comment by dawnpm** [comment]
@margo29 regarding the highlighting @cbukovac mentioned, traditionally the query terms are bolded in search result titles and snippets. Our results API will deliver the results with the query terms already highlighted, but it's up to you how you display that. I would recommend not going with quotation marks, as those have their own meaning, separate from `hey look, here's where what you searched for appears in this text`.

**Comment by margo29** [comment]
@cbukovac & @dawnpm -

Thank you for the feedback. We can certainly extend the box to fit a phrase. As for the quotations @dawnpm - do you know where they call out the code for that? I have looked through the code where it usually is placed, but it is not coming up. I noticed quotes do no display well.

**Comment by margo29** [comment]
@dawnpm - So I have tried to change the "quotes" however it will not disable whatever feature is being applied currently.

Thanks!

**Comment by dawnpm** [comment]
@margo29 the box characters are included in the JSON blob we're delivering in response to the API calls, and this is normal. I'm consulting with my team to see if there's a way we can get github pages to play nicely with them. Other, non-markdown sites don't have an issue with the boxes showing up. For instance OPM [just ignores them entirely](https://www.opm.gov/search/#1402/locality%20pay), and Census does display the [highlighted terms as bold text](https://www.census.gov/search-results.html?q=2020&page=1&stateGeo=none&searchtype=web&cssp=SERP).

**Comment by margo29** [comment]
@dawnpm - okay awesome. Usually these are not an issue, but I know GitHub...gotta be special ;) haha

Any estimate of when we would be able to see them play nicely together? That way I can report back with a possible timeline.

**Comment by thecapacity** [comment]
@dawnpm can you be more specific on the text / character codes that are coming over? (Sorry, I don't have enough knowledge to query the API directly and look).

I'm wondering if maybe there's a way we can filter the character / encoding out and-or set them to not display.

@wslack have you seen this sort of "box behavior" with any of the other Federalist sites?

**Comment by wslack** [comment]
@thecapacity the search results page isn't hosted by Federalist so I'm not sure how or if we could be helpful with that question.

Or, were you talking about the size of the search box?

**Comment by margo29** [comment]
@wslack  - He is referring to the "boxes" around the searched term/word in the list.

We believe it may actually be a GitHub behavior and it is not like the settings of what the API has for the highlighting process, so it is throwing up an "error" for what is suppose to be quotes. I have tried to go through the code to see what I can do to change it, but I may be overlooking where I can change and etc. So any assistance or guidance would be appreciated to get this resolved!

**Comment by wslack** [comment]
Do you have a screenshot? (including a link to the page with the boxes?)

**Comment by dawnpm** [comment]
@wslack the FedRAMP team are using our results API to pull in results for display on their own site, so in this case the results page is indeed hosted on Federalist. our results API delivers JSON, and within that, the query term in each search result is surrounded by box characters, to indicate where highlighting should occur, or not, as the agency design team wishes. In this case, github pages doesn't seem to know how to interpret the characters.

I can provide a link where you (and @thecapacity) can take a look at the JSON blob - could I give that to you in Slack somewhere?

**Comment by wslack** [comment]
I'll need a link; I still don't quite get what's wrong here - unless you are saying that the search results page has “☐” characters showing up everywhere.

**Comment by dawnpm** [comment]
@wslack yes, that's the issue! the `☐` is included in the json blob, and we're a) not sure why github / markdown is just displaying it rather than skipping over it, or b) how to get it to be interpreted as `<strong>` and `</strong>`.

I'll send you a link in Slack.

**Comment by margo29** [comment]
@wslack - here is a screen shot and the url for the demo. Had to deactivate so it doesn't make it to the the live site during a push. 

https://demo.fedramp.gov/search-results/?search=fedramp

![screenshot-2018-4-12 search results fedramp gov](https://user-images.githubusercontent.com/34480828/38677448-509fa728-3e2c-11e8-851a-477be29a711d.png)

**Comment by wslack** [comment]
My best guess is that its a custom piece of unicode intended to be custom interpreted, but I'm not sure. Because browsers display the boxes, I don't think its a Jekyll issue - more that there's some extra functionality to be pulled somehow. cc @line47 if he has any other ideas

**Comment by thecapacity** [comment]
@wslack isn't there some liquid / markdown macro for `| html_escape` (or `-ascii` or `-utf8`) that might filter it out?

**Comment by wslack** [comment]
No idea. If @line47 is busy I can ask Adam to investigate.

**Comment by line47** [comment]
If Adam has availability that would be ideal!

**Comment by wslack** [comment]
Checking!

**Comment by wslack** [comment]
@adborden to scrub in

**Comment by adborden** [comment]
@dawnpm do you have any documentation on the highlight characters? Is this a unicode standard or are you just using unassigned characters and it's on the client to convert these to HTML tags?

**Comment by dawnpm** [comment]
@adborden check out http://unicodesymbols.wikia.com/wiki/%EE%80%80

**Comment by adborden** [comment]
I think we're all set here, should I call out anyone specific to review the PR?

**Comment by thecapacity** [comment]
@adborden probably;

1. @cbukovac so she can test it, and
2. @dawnpm to make sure it matches her expectations (i.e. filtering for `\ue00[01]` just seems strange

I'm also curious if you think a more "global" approach would be better i.e. in line 43 either;
   a. Filtering out all non-ascii; https://stackoverflow.com/questions/20856197/remove-non-ascii-character-in-string
       (specifically `str.replace(/[^\x00-\x7F]/g, "");`
   b. Leveraging this type of approach; https://stackoverflow.com/questions/2670037/how-to-remove-invalid-utf-8-characters-from-a-javascript-string
      (specifically `escape(...)`)

I like the expanded `results.map(...)` function much cleaner.

**Comment by cbukovac** [comment]
@adborden I merged it to demo and it looks great!

**Comment by wslack** [comment]
Can this be closed?

**Comment by cbukovac** [comment]
@wslack I'd be more than happy to close this. I don't know enough about what @thecapacity mentioned above to address it, but maybe we close this issue and if it's critical we can open a new one to handle it.

**Comment by thecapacity** [comment]
@cbukovac if you're happy I'm happy!
