### ISSUE TITLE
Page urls have `//` when they should only have `/`

### ISSUE THREAD

**Issue by line47** [GSA/fedramp-gov#76]
For example when I put the URL`https://fedramp.gov/team/` with out `www` into a browser and hit enter I get taken to `https://www.fedramp.gov//team/` 

Another example `https://fedramp.gov/about/` goes to `https://www.fedramp.gov//about/`

**Notice**
- the first link does not have `www` in the address
- `www` and the double `//` get added somehwere along the way (redirect?)

**Try it out** https://fedramp.gov/about/

**Comment by line47** [comment]
The folks at search.gov are holding off on indexing the new sitemap.xml until this is resolved

**Comment by rhoesing** [comment]
I am working with GSA IT to help solve this.  I will update and close issue when fixed.

**Comment by line47** [comment]
It's fixed! 🎉  thanks @rhoesing
