### ISSUE TITLE
Demo wont build

### ISSUE THREAD

**Issue by cbukovac** [GSA/fedramp-gov#83]
The only change I made was adding a document and a link to that document on the Tips and Cues page, but the builds failed. @wslack is this left over from the gem issue? I've included the build log. 
[build-log-29453.txt](https://github.com/GSA/fedramp-gov/files/1712037/build-log-29453.txt)

**Comment by wslack** [comment]
this was caused by `demo` and `master` being out of sync, which I've now corrected.

**Comment by wslack** [comment]
your added document and link are now live on demo and master both because of how I fixed `demo`

**Comment by cbukovac** [comment]
Interesting, ok thanks!
