### ISSUE TITLE
Updated team page

### ISSUE THREAD

**Issue by pete-gov** [GSA/fedramp-gov#834]
# Goal

We should clearly convey our team, our staffing, and our areas of work.

A member of the public or an agency should be able to quickly see our federal staff leads, their areas of responsibilities, and the size and scope of staff working at the PMO for particular areas of responsibility.

# Request

1. Remove the current FedRAMP team page content and all individual bios
2. Replace content with an updated page showing the organizational structure and general staff counts

# For Example Only

- Office of the Director w/ me, Zaree, Ryan, Marcia, Ryan all listed by names and titles
- Underneath it might say "Communications staff: 4" and "Support staff: 3" etc.
- Then a section for Authorization Branch 
- Underneath, John Hamilton as Program Manager of Security Operations
- Underneath John, it might say "Technical Reviewers: 8" and "Project Managers: 3" etc.

repeat. Open to other ways to do this as well.

**Comment by shivaalipour** [comment]
branch created https://github.com/GSA/fedramp-gov/tree/team-page

**Comment by pete-gov** [comment]
This is great, thank you Shiva! After confirming with Marcia, I'll go ahead and PR that in.
