### ISSUE TITLE
Update new Policy and Guidance Updates page

### ISSUE THREAD

**Issue by pete-gov** [GSA/fedramp-gov#851]
See #850 && https://github.com/GSA/fedramp-gov/tree/pwx-activities

The Policy and Guidance Changes page should reflect all recent, current, and pending policy and guidance changes.

## Motivation

A single source of truth to see the current status of our policy and guidance work.

## Implementation

**Responsible: Experience Branch**

1. **By Tues Nov 5:** Identify all policy and guidance that should be included on the page for initial release
2. **By Tues Nov 5:** Identify the initial overall phases for policy and guidance tracking
3. **By Wed Nov 6:** Populate the page with current content

**Responsible: Web Team**

4. **By Wed Nov 6:** Complete a formatting review and update for readability. We can launch this with it being a bit clumsy or not mobile friendly at first. It should be as easy to update and maintain as possible. Minimum effort. We will revisit later after feedback/etc.

**Content should be ready to launch on Thursday, Nov 7.**

**Comment by kscarf1** [comment]
@david-waltermire  How are we defining/scoping "policy" and "guidance"? Our SOP currently defines "policy," "standard," and "guidelines/guides" here: https://docs.google.com/document/d/1DhN3EqqBtM62vwziZRN2bbwdUZd-R4iTHh4L5jmotyo/edit?tab=t.0#heading=h.n18l9qaezvd0

**Comment by pete-gov** [comment]
> @david-waltermire How are we defining/scoping "policy" and "guidance"? Our SOP currently defines "policy," "standard," and "guidelines/guides" here: https://docs.google.com/document/d/1DhN3EqqBtM62vwziZRN2bbwdUZd-R4iTHh4L5jmotyo/edit?tab=t.0#heading=h.n18l9qaezvd0

This should be specifically for the big picture stuff that we have publicly blogged about, put on our roadmap, or otherwise publicly made some sort of commitment that we are going to do a thing.

**Comment by kscarf1** [comment]
> > @david-waltermire How are we defining/scoping "policy" and "guidance"? Our SOP currently defines "policy," "standard," and "guidelines/guides" here: https://docs.google.com/document/d/1DhN3EqqBtM62vwziZRN2bbwdUZd-R4iTHh4L5jmotyo/edit?tab=t.0#heading=h.n18l9qaezvd0
> 
> This should be specifically for the big picture stuff that we have publicly blogged about, put on our roadmap, or otherwise publicly made some sort of commitment that we are going to do a thing.

Thanks. I'm trying to be at the desired level of "pedantic" here. Usually I would say that anything containing requirements would be in scope, but it sounds like we're looking for things that we've explicitly labeled and promoted as "policy" or "guidance"...?

**Comment by pete-gov** [comment]
> Thanks. I'm trying to be at the desired level of "pedantic" here. Usually I would say that anything containing requirements would be in scope, but it sounds like we're looking for things that we've explicitly labeled and promoted as "policy" or "guidance"...?

Yes, for now that's the scope here, big ticket items with lots of external promotion. This page is to show the status of those things for partners, separate from other more routine changes. i.e., boundary guidance, fips 140 stuff, scuba stuff, low review stuff, metrics, secure configuration profiles, etc. 

This is external facing so it's more about what _other people that aren't us_ see as policy and guidance, not necessarily what we define it as.

**Comment by kscarf1** [comment]
This is awesome, thank you!

**Comment by kscarf1** [comment]
Created a first draft (with placeholders) for the page. Shared with @david-waltermire, who reviewed and added comments for @rpalmer-gsa and me to address.

**Comment by kscarf1** [comment]
Addressed all feedback from @david-waltermire. Will review again after @rpalmer-gsa finishes his additions.

**Comment by pete-gov** [comment]
I'm merging this and considering it good for launch with a few tweaks - let's make sure to revisit in the near future, especially around look and feel. (but also content)
