### ISSUE TITLE
Create initial FedRAMP Platform updates page

### ISSUE THREAD

**Issue by pete-gov** [GSA/fedramp-gov#853]
See #850  && https://github.com/GSA/fedramp-gov/tree/pwx-activities

Prepare a simple initial FedRAMP Platform page that explains what it is and what timelines are being worked towards, with a section at the top to show current status. 

## Motivation

Provide a single source of truth for the public to see what is going on with the FedRAMP Platform.

## Implementation

**Responsible: Experience Team**

1. **By Tues Nov 5:** Create a simple internal content draft, reusing old content as appropriate.

**Responsible: Web Team**

2. **By Wed Nov 6:** Ensure the content meets basic standards for readability/etc. No need to worry about fancy graphics/formatting/etc. for now.

**Content should be ready to launch on Thursday, Nov 7.**

**Comment by david-waltermire** [comment]
@audreamichellewhite and @aj-stein-gsa Can you start drafting some content for this?

**Comment by pete-gov** [comment]
Merged, thank you for your service fam!
