### ISSUE TITLE
Update digital authorization pilot to include new OSCAL Implementer mailing list

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-gov#868]
After the review, approval, merge of https://github.com/GSA/automate.fedramp.gov/pull/117, and deployment of automate.fedramp.gov, we must update the DAP Pilot page to point to new instructions for joining the mailing list directly, not add themselves to the SmartsheetsGov list. This section of the page must have its copy changed and point to [automate.fedramp.gov/contact/#mailing-list](https://automate.fedramp.gov/contact/#mailing-list)

https://github.com/GSA/fedramp-gov/blob/f46315d5ada4ad83dd1e026753c08d9ac94daa39/_layouts/digital-authorization-package-pilot.html#L115

**Comment by aj-stein-gsa** [comment]
@jjahearn22, https://github.com/GSA/automate.fedramp.gov/pull/117 has now been deployed and will end up on the pages on our site.

Can you move forward with making a website to change the aforementioned part of the site I deeplinked in the issue above ☝️?

**Comment by jjahearn22** [comment]
Yes! This will be something I work on this evening

**Comment by jjahearn22** [comment]
@aj-stein-gsa the pull request has been created here: https://github.com/GSA/fedramp-gov/pull/871

**Comment by aj-stein-gsa** [comment]
> @aj-stein-gsa the pull request has been created here: https://github.com/GSA/fedramp-gov/pull/871

I did recommend some capitalization changes but also approved. You can commit those and I'll re-review as necessary. Nice work.

**Comment by aj-stein-gsa** [comment]
Done!
