### ISSUE TITLE
Add link to JAB FAQs

### ISSUE THREAD

**Issue by Marcia-Simms** [GSA/fedramp-gov#900]
Add a link to JAB FAQs on the JAB landing page: https://www.fedramp.gov/updates/jab/

Add the following sentence above the section 'List of 58 Previously JAB Authorized Systems':

JAB Transition FAQs are located in the [FedRAMP Help Center](https://help.fedramp.gov/hc/en-us/sections/31840786131483-JAB-Transition). If you have questions not addressed in any of these FAQs, feel free to contact [info@gsa.gov](mailto:info@gsa.gov) and we will get back to you as soon as we can.

**Comment by pete-gov** [comment]
Minor tweaks to the language but otherwise, it has been shipped.
